sudo: required
dist: trusty
group: edge
os:
    - linux
language: python
python:
    - "3.6"
sources:
       - google-chrome
     packages:		     packages:
       - dpkg  # see https://github.com/travis-ci/travis-ci/issues/9361
       - google-chrome-stable
before_install:
    - google-chrome --version
    
    # Conda
    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"

    # Chromedriver
    - wget https://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip -d $HOME/miniconda/bin
install: 
    - ls
services:
    - docker
