sudo: required
dist: trusty
group: edge
os:
    - linux
language: python
python:
    - "3.6"
addons:
    chrome: stable
before_install:
    - google-chrome --version

    # selenium
    - wget https://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip -d $HOME/miniconda/bin
services:
    - docker
